/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CmMainwweather {
        "data": string;
    }
    interface CmMenu {
        "opened": boolean;
    }
    interface CmMenuItem {
        "data": string;
    }
    interface CmSunmoonimage {
    }
    interface CmTemperature {
        "temp": string;
    }
    interface CmWeather {
        "data": string;
    }
}
export interface CmMenuItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCmMenuItemElement;
}
export interface CmWeatherCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCmWeatherElement;
}
declare global {
    interface HTMLCmMainwweatherElement extends Components.CmMainwweather, HTMLStencilElement {
    }
    var HTMLCmMainwweatherElement: {
        prototype: HTMLCmMainwweatherElement;
        new (): HTMLCmMainwweatherElement;
    };
    interface HTMLCmMenuElement extends Components.CmMenu, HTMLStencilElement {
    }
    var HTMLCmMenuElement: {
        prototype: HTMLCmMenuElement;
        new (): HTMLCmMenuElement;
    };
    interface HTMLCmMenuItemElement extends Components.CmMenuItem, HTMLStencilElement {
    }
    var HTMLCmMenuItemElement: {
        prototype: HTMLCmMenuItemElement;
        new (): HTMLCmMenuItemElement;
    };
    interface HTMLCmSunmoonimageElement extends Components.CmSunmoonimage, HTMLStencilElement {
    }
    var HTMLCmSunmoonimageElement: {
        prototype: HTMLCmSunmoonimageElement;
        new (): HTMLCmSunmoonimageElement;
    };
    interface HTMLCmTemperatureElement extends Components.CmTemperature, HTMLStencilElement {
    }
    var HTMLCmTemperatureElement: {
        prototype: HTMLCmTemperatureElement;
        new (): HTMLCmTemperatureElement;
    };
    interface HTMLCmWeatherElement extends Components.CmWeather, HTMLStencilElement {
    }
    var HTMLCmWeatherElement: {
        prototype: HTMLCmWeatherElement;
        new (): HTMLCmWeatherElement;
    };
    interface HTMLElementTagNameMap {
        "cm-mainwweather": HTMLCmMainwweatherElement;
        "cm-menu": HTMLCmMenuElement;
        "cm-menu-item": HTMLCmMenuItemElement;
        "cm-sunmoonimage": HTMLCmSunmoonimageElement;
        "cm-temperature": HTMLCmTemperatureElement;
        "cm-weather": HTMLCmWeatherElement;
    }
}
declare namespace LocalJSX {
    interface CmMainwweather {
        "data"?: string;
    }
    interface CmMenu {
        "opened"?: boolean;
    }
    interface CmMenuItem {
        "data"?: string;
        "onItemClicked"?: (event: CmMenuItemCustomEvent<string>) => void;
    }
    interface CmSunmoonimage {
    }
    interface CmTemperature {
        "temp"?: string;
    }
    interface CmWeather {
        "data"?: string;
        "onDayclicked"?: (event: CmWeatherCustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "cm-mainwweather": CmMainwweather;
        "cm-menu": CmMenu;
        "cm-menu-item": CmMenuItem;
        "cm-sunmoonimage": CmSunmoonimage;
        "cm-temperature": CmTemperature;
        "cm-weather": CmWeather;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cm-mainwweather": LocalJSX.CmMainwweather & JSXBase.HTMLAttributes<HTMLCmMainwweatherElement>;
            "cm-menu": LocalJSX.CmMenu & JSXBase.HTMLAttributes<HTMLCmMenuElement>;
            "cm-menu-item": LocalJSX.CmMenuItem & JSXBase.HTMLAttributes<HTMLCmMenuItemElement>;
            "cm-sunmoonimage": LocalJSX.CmSunmoonimage & JSXBase.HTMLAttributes<HTMLCmSunmoonimageElement>;
            "cm-temperature": LocalJSX.CmTemperature & JSXBase.HTMLAttributes<HTMLCmTemperatureElement>;
            "cm-weather": LocalJSX.CmWeather & JSXBase.HTMLAttributes<HTMLCmWeatherElement>;
        }
    }
}
