/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CmDate {
        "date": string;
    }
    interface CmMainweather {
        "data": string;
    }
    interface CmSunmoonimage {
    }
    interface CmTemperature {
        "temp": string;
    }
    interface CmWeather {
        "data": string;
    }
}
export interface CmWeatherCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCmWeatherElement;
}
declare global {
    interface HTMLCmDateElement extends Components.CmDate, HTMLStencilElement {
    }
    var HTMLCmDateElement: {
        prototype: HTMLCmDateElement;
        new (): HTMLCmDateElement;
    };
    interface HTMLCmMainweatherElement extends Components.CmMainweather, HTMLStencilElement {
    }
    var HTMLCmMainweatherElement: {
        prototype: HTMLCmMainweatherElement;
        new (): HTMLCmMainweatherElement;
    };
    interface HTMLCmSunmoonimageElement extends Components.CmSunmoonimage, HTMLStencilElement {
    }
    var HTMLCmSunmoonimageElement: {
        prototype: HTMLCmSunmoonimageElement;
        new (): HTMLCmSunmoonimageElement;
    };
    interface HTMLCmTemperatureElement extends Components.CmTemperature, HTMLStencilElement {
    }
    var HTMLCmTemperatureElement: {
        prototype: HTMLCmTemperatureElement;
        new (): HTMLCmTemperatureElement;
    };
    interface HTMLCmWeatherElement extends Components.CmWeather, HTMLStencilElement {
    }
    var HTMLCmWeatherElement: {
        prototype: HTMLCmWeatherElement;
        new (): HTMLCmWeatherElement;
    };
    interface HTMLElementTagNameMap {
        "cm-date": HTMLCmDateElement;
        "cm-mainweather": HTMLCmMainweatherElement;
        "cm-sunmoonimage": HTMLCmSunmoonimageElement;
        "cm-temperature": HTMLCmTemperatureElement;
        "cm-weather": HTMLCmWeatherElement;
    }
}
declare namespace LocalJSX {
    interface CmDate {
        "date"?: string;
    }
    interface CmMainweather {
        "data"?: string;
    }
    interface CmSunmoonimage {
    }
    interface CmTemperature {
        "temp"?: string;
    }
    interface CmWeather {
        "data"?: string;
        "onDayclicked"?: (event: CmWeatherCustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "cm-date": CmDate;
        "cm-mainweather": CmMainweather;
        "cm-sunmoonimage": CmSunmoonimage;
        "cm-temperature": CmTemperature;
        "cm-weather": CmWeather;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cm-date": LocalJSX.CmDate & JSXBase.HTMLAttributes<HTMLCmDateElement>;
            "cm-mainweather": LocalJSX.CmMainweather & JSXBase.HTMLAttributes<HTMLCmMainweatherElement>;
            "cm-sunmoonimage": LocalJSX.CmSunmoonimage & JSXBase.HTMLAttributes<HTMLCmSunmoonimageElement>;
            "cm-temperature": LocalJSX.CmTemperature & JSXBase.HTMLAttributes<HTMLCmTemperatureElement>;
            "cm-weather": LocalJSX.CmWeather & JSXBase.HTMLAttributes<HTMLCmWeatherElement>;
        }
    }
}
